#!/usr/bin/ruby
# frozen_string_literal: true

require 'zip'
require 'highline'
require 'shellwords'
require 'tempfile'
require 'fileutils'
require 'irc/books/context'
def main
  context = Irc::Books::Context.new

  context.start
end

main
